DROP DATABASE IF EXISTS myPlayer;
CREATE DATABASE myPlayer;
USE myPlayer;

CREATE TABLE directory (
	id INT NOT NULL AUTO_INCREMENT,
	path VARCHAR(128) NOT NULL,
	ts TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE playlist (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	songPath VARCHAR(256) NOT NULL,
	deleted TINYINT(1) NOT NULL,
	PRIMARY KEY(id)
);

ALTER TABLE playlist ALTER deleted SET DEFAULT 0;